default: &default
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 4

production: &production
  <<: *default
  database: elmo_production

mysql_data_source: &pii
  hostname: localhost
  port: 3306
  username: root
  password:
  database: elmo_production

mysql2psql:
  mysql:
    <<: *pii

  destination:
    production:
      <<: *production

  # If suppress_data is true, only the schema definition will be exported/migrated, and not the data
  suppress_data: false

  # If suppress_ddl is true, only the data will be exported/imported, and not the schema
  suppress_ddl: false

  # If force_truncate is true, forces a table truncate before table loading
  force_truncate: true

  preserve_order: false

  remove_dump_file: true

  dump_file_directory: /tmp

  report_status: json    # false, json, xml

  # If clear_schema is true, the public schema will be recreated before conversion
  # The import will fail if both clear_schema and suppress_ddl are true.
  clear_schema: true
