test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  access_key_id: <%= ENV["NEMO_AWS_ACCESS_KEY_ID"].presence %>
  service: S3
  secret_access_key: <%= ENV["NEMO_AWS_SECRET_ACCESS_KEY"].presence %>
  region: <%= ENV["NEMO_AWS_REGION"].presence %>
  bucket: <%= ENV["NEMO_AWS_BUCKET"].presence %>
